trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseTerraform@0
    inputs:
      command: 'init'
      workingDirectory: '$(Build.SourcesDirectory)/terraform'
      backendServiceArm: 'AzureServiceConnection'
      backendAzureRmResourceGroupName: 'terraform-backend-rg'
      backendAzureRmStorageAccountName: 'terraformbackendstorage'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'cosmicStorage.tfstate'
  - task: UseTerraform@0
    inputs:
      command: 'validate'
      workingDirectory: '$(Build.SourcesDirectory)/terraform'
  - task: UseTerraform@0
    inputs:
      command: 'plan'
      workingDirectory: '$(Build.SourcesDirectory)/terraform'
      environmentServiceName: 'AzureServiceConnection'
      additionalArgs: '-out=$(Build.SourcesDirectory)/terraform/plan.out'
