trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseTerraform@0
    inputs:
      command: 'apply'
      workingDirectory: '$(Build.SourcesDirectory)/terraform'
      environmentServiceName: 'AzureServiceConnection'
      additionalArgs: '-auto-approve $(Build.SourcesDirectory)/terraform/plan.out'
