trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Running Terraform Compliance Tests"
      cd $(Build.SourcesDirectory)/terraform
      terraform-compliance -p plan.out
    displayName: 'Terraform Compliance Test'
